### ISSUE TITLE
Ctrl-Bkspace deletes entire tree

### ISSUE THREAD

**Issue by rzach** [gleachkr/ProofJS#2]
Ctrl+Backspace deletes not just the node, but the entire subproof ending in the node. That may be very unintended, and without an "undo" can be frustrating.

Better, perhaps: delete the node, and make any parent node a parent node of the conclusion if possible. (Not always possible, eg if last node in proof has more than one premise)

Even better: a for fix issue #1 would allow same functionality but without being surprised that the entire proof is gone.

**Comment by gleachkr** [comment]
Partly fixed by adding undo in 3cab8bb. I'll leave this open unti we've got #1, though.

**Comment by gleachkr** [comment]
OK, we've closed #1, so I think this is OK to close.
